services:
  - type: web
    name: youtube-longform-n8n
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /healthz/readiness
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "https"
      - key: GENERIC_TIMEZONE
        value: "Europe/Madrid"
      - key: DB_TYPE
        value: "postgresdb"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_VERSION_NOTIFICATIONS_ENABLED
        value: "false"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"
      - key: DB_POSTGRESDB_DATABASE
        sync: false
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: N8N_EDITOR_BASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
